### ISSUE TITLE
Integration with Format-BLE-Tracker?

### ISSUE THREAD

**Issue by jherland** [EverythingSmartHome/everything-presence-one#205]
I'm playing around with room presence using BLE tracking from https://github.com/formatBCE/Format-BLE-Tracker, and the associated ESPHome integration at https://github.com/formatBCE/ESP32_BLE_presense. I've tried adding the requisite configuration to my EP1's configuration:

```
esphome:
  ...
  includes:
    - ble-node.h  # source available here: https://github.com/formatBCE/ESP32_BLE_presense/blob/main/esphome/ble-node.h
  libraries:
    - "h2zero/NimBLE-Arduino"

mqtt:
  broker: 192.168.0.1
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true

custom_component:
- lambda: |-
    auto my_node = new BleNodeComponent("home_office");
    return {my_node};
```

but it fails to build with this error:

```
Compiling .pioenvs/everything-presence-one-ec5e2c/src/main.o
[...]
In file included from src/main.cpp:237:
src/ble-node.h:11:10: fatal error: Arduino.h: No such file or directory

*****************************************************************
* Looking for Arduino.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Arduino.h"
* Web  > https://registry.platformio.org/search?q=header:Arduino.h
*
*****************************************************************

 #include <Arduino.h>
          ^~~~~~~~~~~
compilation terminated.
*** [.pioenvs/everything-presence-one-ec5e2c/src/main.o] Error 1
```

I'm quite new to the ESPHome ecosystem, and I suspect that I am attempting something that is not supported (or even possible) on the EP1 here?

Any help appreciated, whether it be how to proceed to get this working, or more generally, how to set up the EP1 to support room presence BLE tracking.

**Comment by EverythingSmartHome** [comment]
Hello!

Sorry this wouldn't be a supported request for this repo, purely because it's community made and I haven't ever tried or tested it. Please, by all means continue to tinker with it, it looks like a cool project, I just won't be able to support it.

If I had to guess, I would guess it only works with the Arduino framework, where as the EP1 uses esp-idf framework instead due to better Bluetooth performance. That's just a guess though, it could be completely wrong!
