### ISSUE TITLE
EP1 as bluetooth proxy for home assistant?

### ISSUE THREAD

**Issue by amaisano** [EverythingSmartHome/everything-presence-one#3]
Does the hardware include bluetooth w/active scanning? I was thinking of also using this wonderful device as a BT proxy for some of my home assistant needs.

Is BT enabled?

**Comment by amaisano** [comment]
Tried adding this to the HA Add-on config:

https://www.home-assistant.io/integrations/bluetooth#esphome-requirements

```yaml
esp32_ble_tracker:
bluetooth_proxy:
```

```
Failed config

esp32_improv: [source /config/esphome/.esphome/packages/f43db209/everything-presence-one.yaml:33]
  
  Component esp32_improv cannot be used together with component esp32_ble_tracker.
  authorizer: none
esp32_ble_server: None
  {}
esp32_ble: None
  {}
Component esp32_ble_server cannot be used together with component esp32_ble_tracker

Component esp32_ble cannot be used together with component esp32_ble_tracker
```

I am very new to ESP32 (this is my first device) so I think I just need some guidance.

**Comment by EverythingSmartHome** [comment]
Hello!

BT tracking and BT Proxy is disabled by default because it conflicts currently with Improv (which is used for initial setup) - in the future it should be possible to have them on at the same time but currently it meant we had to disable them to allow for easy setup.

They can of course be added after setup. You will need to firstly create your own ESPHome config if you haven't already done so - you can copy the full EP1 config and paste it in using the config from here: https://github.com/EverythingSmartHome/everything-presence-one/blob/main/everything-presence-one.yaml

Replace the WiFi section of this config which currently looks like:

```
wifi:
  ap {}
```

with this:

```
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

You will also need to remove the section that says:
```
esp32_improv:
  authorizer: none
```

And add the following lines back in:
```
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
```

Finally make sure there are no errors, save the config and then install the new config to the EP1.

**Comment by amaisano** [comment]
SO, something like this?

https://github.com/EverythingSmartHome/everything-presence-one/compare/main...amaisano:everything-presence-one:patch-1

And then I just use the HA Add-On dashboard and click "Save" and then "Install" with those file contents?

I'm so afraid of "breaking" the EP1 functionality.

**Comment by EverythingSmartHome** [comment]
> SO, something like this?
> 
> [main...amaisano:everything-presence-one:patch-1](https://github.com/EverythingSmartHome/everything-presence-one/compare/main...amaisano:everything-presence-one:patch-1)
> 
> And then I just use the HA Add-On dashboard and click "Save" and then "Install" with those file contents?
> 
> I'm so afraid of "breaking" the EP1 functionality.

Looks good to me!

You can't really break the functionality - if you make a mistake then you can simply use the flash page here to restore to factory firmware:

https://everythingsmarthome.github.io/everything-presence-one/flashing.html

If you get stuck then feel free to join the Discord which might be easier to talk you through.

**Comment by amaisano** [comment]
RESOLVED

The proposed patch (a combination of the original configuration from EP1 and some additional changes for BT proxy support) works perfectly, but getting it into the EP1 needed some alternative/additional steps.

From the man @EverythingSmartHome himself:

- Since you don't have HTTPS enabled you'll have to do a bit more work
- Safe mode ON anytime you want to do an OTA update (adjusting config/settings wirelessly)
- [Skip installing when adopting things in Add-On]
- [In HA ESP Home Add-On] press install then manual download and choose modern
- Download the file it gives
- Then go to web.esphome.io and install the firmware using that website (over USB)

**Comment by nstrelow** [comment]
Just found this, because I was wondering if the ble_proxy was enabled by default and couldn't find it in the config.

@EverythingSmartHome 
Might by worth sticking this or some explanation on why this is not added by default, with this issue are a small guide on how to enable it.
Since bluetooth proxy being an option is advertised on the shop (and also on the board, love the markings. USB C baby 🥳 )

**Comment by dhuddle** [comment]
Has anyone tested this for a bit? I’m setting up my EP1’s now and I’m interested in turning on the proxy function, but as I’ve done this on another (different) esphome device I had and I found that it caused that device to behave a bit strangely.

**Comment by nstrelow** [comment]
No idea how it should behave weirdly. If bluetooth is not used for anything else. Power consumption might go up.

**Comment by amaisano** [comment]
Mine IS actually behaving weirdly. But I cannot be sure if it is from before or after the proxy config setup. It is constantly disconnecting/becoming unknown/unavailble in HA.

![image](https://user-images.githubusercontent.com/688435/211641486-2846db37-bd1f-484d-a18d-e581eb026408.png)

**Comment by EverythingSmartHome** [comment]
> Mine IS actually behaving weirdly. But I cannot be sure if it is from before or after the proxy config setup. It is constantly disconnecting/becoming unknown/unavailble in HA.
> 
> ![image](https://user-images.githubusercontent.com/688435/211641486-2846db37-bd1f-484d-a18d-e581eb026408.png)

These seems to happen on a couple users WiFi for some reason - the fix we found is to either update to ESPHome beta 2023.1 or to adjust the power saving mode in the config to "none":

https://esphome.io/components/wifi.html#wifi-power-save-mode

It does seem to be Bluetooth related and one user mentioned 2023.1 beta does fix it for him.

**Comment by amaisano** [comment]
> adjust the power saving mode in the config to "none":

  power_save_mode NONE is incompatible with esp32_ble_tracker. Please remove the power save mode. See also https://github.com/esphome/issues/issues/2141#issuecomment-865688582.
